---
site_name: "OSC-EM Schemas"
site_dir: site/
docs_dir: docs/
site_url: https://osc-em.github.io/oscem-schemas
site_author: OSC-EM
repo_url: https://github.com/osc-em/oscem-schemas
repo_name: GitHub

theme:
  name: material
  logo: https://raw.githubusercontent.com/osc-em/osc-em.github.io/refs/heads/main/docs/assets/img/oscem_icon.svg
  favicon: https://raw.githubusercontent.com/osc-em/osc-em.github.io/refs/heads/main/docs/assets/img/oscem_icon.svg
  palette:
    primary: grey
    accent: cyan
  features:
    - navigation.sections
    - navigation.expand
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.tabs.link
edit_uri: ""
plugins:
  - search
  - mermaid2:
      version: 10.9.0
nav:
  - Home: https://osc-em.github.io/
  - Overview: index.md
  - Artifacts: artifacts.md
  - Schemas:
    - General: general/index.md
    - SPA: spa/index.md
    - Subtomogram Averaging: subtomo/index.md
    - Environmental Tomography: env_tomo/index.md
    - Cellular Tomography: cellular_tomo/index.md
